[build]
  publish = "dist"
  command = "pnpm run build"
  environment = { NODE_VERSION = "22" }

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
